# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQ4qG-tRp0fWqROB9zSl1cteazzZXtqI
"""

import streamlit as st
from streamlit_option_menu import option_menu

# -------------------- PAGE CONFIG --------------------
st.set_page_config(page_title="Futura Systems", layout="wide")

# -------------------- DARK THEME STYLING --------------------
st.markdown("""
    <style>
    .stApp {
        background-color: #000000 !important;
    }

    .block-container {
        padding-top: 1rem !important;
        padding-bottom: 1rem !important;
    }

    html, body, .stApp, .block-container, .markdown-text-container, .css-1v3fvcr {
        color: #ffffff !important;
        font-size: 17px !important;
    }

    h1, h2, h3, h4 {
        color: #33FFEC !important;
    }

    [data-testid="stHorizontalBlock"] {
        z-index: 2;
        position: relative;
    }

    .nav-item {
        margin-right: 10px !important;
    }

    .nav-link {
        width: 100% !important;
        padding: 10px 20px !important;
        display: flex !important;
        align-items: center !important;
        justify-content: center !important;
        border-radius: 8px !important;
    }
    </style>
""", unsafe_allow_html=True)

# -------------------- SITE TITLE ABOVE MENU --------------------
st.markdown("""
    <h2 style='text-align: center; color: #33FFEC; margin-bottom: 0; font-weight: bold;'>
        Futura Systems
    </h2>
""", unsafe_allow_html=True)

# -------------------- NAVIGATION MENU --------------------
selected = option_menu(
    menu_title=None,
    options=["Home", "About Us", "Services", "Careers", "Contact"],
    icons=["house", "info-circle", "briefcase", "person-lines-fill", "envelope"],
    orientation="horizontal",
    default_index=0,
    styles={
        "container": {"padding": "0!important", "background-color": "#111"},
        "icon": {"color": "#33FFEC", "font-size": "18px"},
        "nav-link": {
            "font-size": "18px",
            "text-align": "center",
            "margin": "0px 5px",
            "padding": "10px 20px",
            "border-radius": "6px",
            "--hover-color": "#222",
        },
        "nav-link-selected": {"background-color": "#04f0fc", "color": "#000"},
    }
)

# -------------------- HOME PAGE --------------------
if selected == "Home":
    st.title("🚀 Welcome to Futura Systems")
    st.subheader("Next-Gen AI Solutions for Businesses and Innovators")
    st.markdown("We help individuals and organizations unleash the power of AI.")
    st.markdown("- 🤖 AI Agents for Support and Automation")
    st.markdown("- 📈 Data Insights to drive decision-making")
    st.markdown("- 🛠️ Tailored AI to solve unique challenges")

    st.markdown("---")

    # Newsletter Signup
    st.markdown("### 📬 Join Our Newsletter")
    with st.form("newsletter_form"):
        email = st.text_input("Enter your email")
        submitted = st.form_submit_button("Subscribe")
        if submitted and email:
            st.success(f"✅ Thank you for subscribing, {email}!")
        elif submitted:
            st.error("❌ Please enter a valid email.")

# -------------------- ABOUT US PAGE --------------------
elif selected == "About Us":
    st.title("About Us: Empowering Your Business with AI")
    st.markdown("""
At **Futura Systems**, we believe that cutting-edge Artificial Intelligence shouldn't be exclusive to large corporations.
We're a passionate team dedicated to bringing the transformative power of AI directly to individual businesses like yours, helping you solve challenges, optimize operations, and unlock new growth opportunities.
""")
    st.markdown("## 🎯 Our Mission")
    st.markdown("""
To make advanced AI accessible and actionable for every individual business.
We empower entrepreneurs and SMEs with intelligent solutions that drive efficiency, enhance decision-making, and foster sustainable success in an increasingly digital world.
""")
    st.markdown("## 🔭 Our Vision")
    st.markdown("""
We envision a future where every individual business, regardless of its size, can harness the full potential of AI to thrive.
We aim to be your trusted partner through your AI journey — demystifying complex technologies and delivering **tangible, impactful results**.
""")
    st.markdown("## ✅ Why Choose Us?")
    st.markdown("""
- **Tailored Solutions:** No one-size-fits-all. We build what **you** need.
- **Practical & Impactful:** We focus on delivering **measurable** value.
- **Expert Team:** Experienced AI specialists + business strategists.
- **Client-Centric Approach:** Your goals = our mission.
- **Affordable & Accessible:** Big AI, even for small businesses.
""")
    st.markdown("## 📞 Connect With Us")
    st.markdown("""
**Ready to see how AI can transform your business?**
Contact us today and let’s build your AI-powered future — together.
""")

# -------------------- SERVICES PAGE --------------------
elif selected == "Services":
    st.header("Our Services")
    st.markdown("""
    <div style='font-size:20px; line-height:1.8;'>
    At <strong>Futura Systems</strong>, we provide a wide range of AI-powered services tailored to your business needs:

    - 🔍 <strong>AI Strategy & Consultation</strong>: Expert guidance to help you integrate AI seamlessly into your operations.
    - 🧠 <strong>Custom AI Solutions</strong>: From predictive modeling to process automation — we design solutions built just for your unique challenges.
    - 📊 <strong>Business Intelligence & Insights</strong>: Turn raw data into actionable decisions with intelligent dashboards and reporting.
    - 🤖 <strong>AI Agents & Automation</strong>: Deploy smart virtual assistants, chatbots, and automation pipelines to increase efficiency.
    - 🧾 <strong>Document Intelligence</strong>: Automatically extract, analyze, and classify business documents and contracts using AI.
    - 💡 <strong>Use-Case Discovery Workshops</strong>: Identify hidden opportunities in your business that can benefit from AI.

    <br>
    <strong>Let us be your AI partner — transforming business problems into intelligent solutions.</strong>
    </div>
    """, unsafe_allow_html=True)

# -------------------- CAREERS PAGE --------------------
elif selected == "Careers":
    st.header("Careers")
    st.info("📢 No openings yet. Stay tuned!")

# -------------------- CONTACT PAGE --------------------
elif selected == "Contact":
    st.header("Contact")
    st.markdown("📧 **Email:** ramishashraf95@gmail.com")
    st.markdown("💬 **WhatsApp:** +923004890771 *(placeholder)*")